from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ('app', '0001_initial'),
        ('app', '0002_billing_snapshots'),
        ('app', '0003_billingdetail_unit_price'),
        ('app', '0004_remove_companymember_first_cycle_completed_and_more'),
        ('app', '0005_systemsettings_base_font_size_and_more'),
        ('app', '0006_systemsettings_chart_title_font_size'),
        ('app', '0007_systemsettings_branding_fields'),
        ('app', '0008_companymember_first_cycle_fields'),
        ('app', '0009_remove_companymember_first_cycle_completed_and_more'),
        ('app', '0010_readd_companymember_first_cycle_fields'),
        ('app', '0011_alter_user_email'),
        ('app', '0012_companymember_additional_fields'),
        ('app', '0013_companymember_sex'),
        ('app', '0014_systemsettings_btn_clear_filter_bg_and_more'),
        ('app', '0015_rename_company_identification_document'),
        ('app', '0016_alter_systemsettings_list_item_background_color'),
        ('app', '0017_systemsettings_support_email'),
        ('app', '0018_companymember_user_user_sync_member_profile_and_more'),
        ('app', '0019_remove_permission_userpermission'),
    ]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cutoff_day', models.IntegerField(default=15, help_text='Dia do mês para corte de cobrança integral', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dia de Corte')),
                ('default_bill_admin_users', models.BooleanField(default=False, verbose_name='Cobrar Admin da Empresa por Padrão')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, max_length=200, verbose_name='SMTP User')),
                ('smtp_password', models.CharField(blank=True, max_length=200, verbose_name='SMTP Password')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor Secundária')),
                ('system_name', models.CharField(default='Sistema Multi-Empresas', max_length=200, verbose_name='Nome do Sistema')),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='Logo do Sistema')),
                ('login_background_url', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='Background Login')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('base_font_size', models.CharField(blank=True, default='16px', max_length=10, verbose_name='Tamanho Base da Fonte')),
                ('btn_danger_bg', models.CharField(blank=True, default='#dc3545', max_length=7, verbose_name='Cor do Botão de Perigo')),
                ('btn_danger_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto de Perigo')),
                ('btn_export_bg', models.CharField(blank=True, default='#0dcaf0', max_length=7, verbose_name='Cor do Botão de Exportação')),
                ('btn_export_text', models.CharField(blank=True, default='#212529', max_length=7, verbose_name='Cor do Texto do Botão de Exportação')),
                ('btn_filter_bg', models.CharField(blank=True, default='#0d6efd', max_length=7, verbose_name='Cor do Botão de Filtro')),
                ('btn_filter_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto do Botão de Filtro')),
                ('btn_import_bg', models.CharField(blank=True, default='#198754', max_length=7, verbose_name='Cor do Botão de Importação')),
                ('btn_import_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto do Botão de Importação')),
                ('btn_info_bg', models.CharField(blank=True, default='#17a2b8', max_length=7, verbose_name='Cor do Botão de Informação')),
                ('btn_info_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto de Informação')),
                ('btn_primary_bg', models.CharField(blank=True, default='#0d6efd', max_length=7, verbose_name='Cor do Botão Primário')),
                ('btn_primary_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto do Botão Primário')),
                ('btn_secondary_bg', models.CharField(blank=True, default='#6c757d', max_length=7, verbose_name='Cor do Botão Secundário')),
                ('btn_secondary_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto do Botão Secundário')),
                ('btn_success_bg', models.CharField(blank=True, default='#198754', max_length=7, verbose_name='Cor do Botão de Sucesso')),
                ('btn_success_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto de Sucesso')),
                ('btn_warning_bg', models.CharField(blank=True, default='#ffc107', max_length=7, verbose_name='Cor do Botão de Alerta')),
                ('btn_warning_text', models.CharField(blank=True, default='#212529', max_length=7, verbose_name='Cor do Texto de Alerta')),
                ('heading_font_size', models.CharField(blank=True, default='1.75rem', max_length=10, verbose_name='Tamanho da Fonte dos Títulos')),
                ('link_color', models.CharField(blank=True, default='#0d6efd', max_length=7, verbose_name='Cor dos Links')),
                ('sidebar_active_bg', models.CharField(blank=True, default='#1f2d3d', max_length=7, verbose_name='Cor do Item Ativo do Sidebar')),
                ('sidebar_active_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto Ativo do Sidebar')),
                ('sidebar_bg', models.CharField(blank=True, default='#2c3e50', max_length=7, verbose_name='Cor do Fundo do Sidebar')),
                ('sidebar_font_size', models.CharField(blank=True, default='0.95rem', max_length=10, verbose_name='Tamanho da Fonte do Sidebar')),
                ('sidebar_text', models.CharField(blank=True, default='#f8f9fa', max_length=7, verbose_name='Cor do Texto do Sidebar')),
                ('chart_title_font_size', models.CharField(blank=True, default='1.25rem', max_length=10, verbose_name='Tamanho dos Títulos de Gráficos')),
                ('page_background_color', models.CharField(blank=True, default='#f5f7fa', max_length=7, verbose_name='Cor de Fundo das Páginas')),
                ('custom_favicon', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='Favicon Personalizado')),
                ('custom_domain', models.URLField(blank=True, max_length=255, verbose_name='Domínio personalizado')),
                ('use_custom_domain', models.BooleanField(default=False, verbose_name='Usar domínio personalizado')),
                ('btn_clear_filter_bg', models.CharField(blank=True, default='#6c757d', max_length=7, verbose_name='Cor do Botão de Limpar Filtros')),
                ('btn_clear_filter_text', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto do Botão de Limpar Filtros')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='Texto do Rodapé')),
                ('list_item_background_color', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor de Fundo das Linhas de Tabela')),
                ('show_footer_text', models.BooleanField(default=False, verbose_name='Exibir texto do rodapé')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de suporte')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('identification_document', models.CharField(max_length=50, unique=True, verbose_name='Documento de identificação Fiscal')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('member_price', models.DecimalField(decimal_places=2, help_text='Usado quando billing_mode = per_user', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço por Membro')),
                ('bill_admin_users', models.BooleanField(default=False, verbose_name='Cobra Admin da Empresa')),
                ('currency', models.CharField(choices=[('BRL', 'Real Brasileiro (R$)'), ('USD', 'Dólar Americano ($)'), ('EUR', 'Euro (€)'), ('MXN', 'Peso Mexicano ($)')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('currency_symbol', models.CharField(default='R$', max_length=5, verbose_name='Símbolo da Moeda')),
                ('billing_mode', models.CharField(choices=[('per_user', 'Por Usuário'), ('per_user_chatbot', 'Por Usuário/Chatbot')], default='per_user', max_length=20, verbose_name='Modo de Cobrança')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_cycle_completed', models.BooleanField(default=False, verbose_name='Primeiro ciclo concluído')),
                ('first_cycle_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Snapshot de Preço (1º ciclo)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Base')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_company', 'Admin da Empresa')], default='admin_company', max_length=20, verbose_name='Papel')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('sync_member_profile', models.BooleanField(default=True, help_text='Quando habilitado, cria ou atualiza um membro vinculado a este admin.', verbose_name='Considerar como membro')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('identification_document', models.CharField(max_length=50, unique=True, verbose_name='Documento de identificação')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('dealership', models.CharField(blank=True, max_length=200, verbose_name='Concessionária')),
                ('dealership_number', models.CharField(blank=True, max_length=50, verbose_name='Número da Concessionária')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_cycle_completed', models.BooleanField(default=False, verbose_name='Primeiro ciclo concluído')),
                ('first_cycle_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Snapshot de Preço (1º ciclo)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='País')),
                ('regional', models.CharField(blank=True, max_length=120, verbose_name='Regional')),
                ('role_type', models.CharField(blank=True, choices=[('management', 'Gerencial'), ('operational', 'Operacional'), ('technical', 'Técnico'), ('support', 'Suporte'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de cargo')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='Estado')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro'), ('prefer_not', 'Prefere não informar')], max_length=20, verbose_name='Sexo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.company', verbose_name='Empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Administrador')),
            ],
            options={
                'verbose_name': 'Membro da Empresa',
                'verbose_name_plural': 'Membros da Empresa',
                'ordering': ['name'],
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='app.company', verbose_name='Empresa')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings_generated', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-period_start', 'company__name'],
                'unique_together': {('company', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CompanyChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o preço base do chatbot', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Customizado')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_chatbots', to='app.chatbot', verbose_name='Chatbot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_chatbots', to='app.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Chatbot da Empresa',
                'verbose_name_plural': 'Chatbots das Empresas',
                'ordering': ['company__name', 'chatbot__name'],
                'unique_together': {('company', 'chatbot')},
            },
        ),
        migrations.CreateModel(
            name='MemberChatbotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField(verbose_name='Data de Ativação')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_cycle_completed', models.BooleanField(default=False, verbose_name='Primeiro ciclo concluído')),
                ('first_cycle_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Snapshot de Preço (1º ciclo)')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accesses', to='app.chatbot', verbose_name='Chatbot')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_accesses', to='app.companymember', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Acesso ao Chatbot',
                'verbose_name_plural': 'Acessos aos Chatbots',
                'ordering': ['member__name', 'chatbot__name'],
                'unique_together': {('member', 'chatbot')},
            },
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField(verbose_name='Data de Ativação')),
                ('days_active', models.IntegerField(verbose_name='Dias Ativos')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarifa Diária')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('billing_type', models.CharField(choices=[('full', 'Integral'), ('proportional', 'Proporcional')], max_length=15, verbose_name='Tipo de Cobrança')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.billing', verbose_name='Cobrança')),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_details', to='app.chatbot', verbose_name='Chatbot')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_details', to='app.companymember', verbose_name='Membro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_details', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Detalhe da Cobrança',
                'verbose_name_plural': 'Detalhes das Cobranças',
                'ordering': ['billing', 'member__name'],
            },
        ),
        migrations.CreateModel(
            name='UserStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], max_length=10, verbose_name='Status')),
                ('date_start', models.DateField(verbose_name='Data Início')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.companymember', verbose_name='Membro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('super_admin_created', 'Super Admin Criado'), ('billing_generated', 'Cobrança Gerada'), ('member_price_changed', 'Preço de Membro Alterado'), ('login_failed', 'Login Falhou'), ('billing_mode_changed', 'Modo de Cobrança Alterado'), ('chatbot_linked', 'Chatbot Vinculado'), ('chatbot_unlinked', 'Chatbot Desvinculado'), ('member_status_changed', 'Status de Membro Alterado')], max_length=50, verbose_name='Ação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
