# Generated by Django 4.2.7 on 2026-06-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_memberchatbotaccess_deactivation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('super_admin_created', 'Super Admin Criado'), ('company_created', 'Empresa Criada'), ('company_deleted', 'Empresa Deletada'), ('settings_updated', 'Configurações Atualizadas'), ('billing_generated', 'Cobrança Gerada'), ('member_price_changed', 'Preço de Membro Alterado'), ('login_failed', 'Login Falhou'), ('billing_mode_changed', 'Modo de Cobrança Alterado'), ('chatbot_linked', 'Chatbot Vinculado'), ('chatbot_unlinked', 'Chatbot Desvinculado'), ('member_status_changed', 'Status de Membro Alterado')], max_length=50, verbose_name='Ação'),
        ),
    ]
